(define (problem rpggame_1)
(:domain rpggame)
(:objects
	r1 r2 r3 r4 r5 r6 r7 r8 - room
)
(:init
    (in r1)

	(empty_handed)

	(unexplored r2)
	(unexplored r3)
	(unexplored r4)
	(unexplored r5)
	(unexplored r6)
	(unexplored r7)
	(unexplored r8)

	(not_have_sword r1)
	(have_sword r2)
	(not_have_sword r3)
	(not_have_sword r4)
	(not_have_sword r5)
	(not_have_sword r6)
	(not_have_sword r7)
	(not_have_sword r8)

	(not_have_trap r1)
	(not_have_trap r2)
	(not_have_trap r3)
	(have_trap r4)
	(not_have_trap r5)
	(not_have_trap r6)
	(not_have_trap r7)
	(not_have_trap r8)

	(not_have_monster r1)
	(not_have_monster r2)
	(have_monster r3)
	(not_have_monster r4)
	(not_have_monster r5)
	(not_have_monster r6)
	(not_have_monster r7)
	(have_monster r8)

	(connected r1 r2)
	(connected r2 r1)
	(connected r2 r3)
	(connected r3 r2)
	(connected r3 r4)
	(connected r4 r3)
	(connected r4 r5)
	(connected r5 r4)
	(connected r4 r6)
	(connected r6 r4)
	(connected r6 r7)
	(connected r7 r6)
	(connected r7 r8)
	(connected r8 r7)
	(connected r8 r2)
	(connected r2 r8)
	(connected r3 r7)
	(connected r7 r3)
	(connected r1 r8)
	(connected r8 r1)

)
(:goal (and
    (in r5)
)))
